#ifndef KERNELS_H
#define KERNELS_H
#include "../../include/typedefs.h"
#include <cfloat>
#include <cuda.h>
#include <cuda_runtime_api.h>

extern "C" void cuda_convcell_propagate(unsigned int nbChannels,
                                        unsigned int channelsHeight,
                                        unsigned int channelsWidth,
                                        unsigned int paddingY,
                                        unsigned int paddingX,
                                        unsigned int strideY,
                                        unsigned int strideX,
                                        unsigned int subSampleY,
                                        unsigned int subSampleX,
                                        const DATA_T* inputs,
                                        unsigned int oySize,
                                        unsigned int oxSize,
                                        unsigned int nbOutputs_,
                                        unsigned int outputsHeight,
                                        unsigned int outputsWidth,
                                        unsigned int nbOutputs,
                                        unsigned int outputOffset,
                                        DATA_T* outputs,
                                        unsigned int kernelHeight,
                                        unsigned int kernelWidth,
                                        const BDATA_T* bias,
                                        const WDATA_T* weights,
                                        ActivationFunction_T func,
                                        int shift,
                                        dim3 threadsPerBlocks,
                                        dim3 blocksPerGrid,
                                        bool isProfiled,
                                        float* exec_time);

extern "C" void cuda_convcell_upropagate(unsigned int nbChannels,
                                         unsigned int channelsHeight,
                                         unsigned int channelsWidth,
                                         unsigned int paddingY,
                                         unsigned int paddingX,
                                         unsigned int strideY,
                                         unsigned int strideX,
                                         unsigned int subSampleY,
                                         unsigned int subSampleX,
                                         const UDATA_T* inputs,
                                         unsigned int oySize,
                                         unsigned int oxSize,
                                         unsigned int nbOutputs_,
                                         unsigned int outputsHeight,
                                         unsigned int outputsWidth,
                                         unsigned int nbOutputs,
                                         unsigned int outputOffset,
                                         DATA_T* outputs,
                                         unsigned int kernelHeight,
                                         unsigned int kernelWidth,
                                         const BDATA_T* bias,
                                         const WDATA_T* weights,
                                         ActivationFunction_T func,
                                         int shift,
                                         dim3 threadsPerBlocks,
                                         dim3 blocksPerGrid,
                                         bool isProfiled,
                                         float* exec_time);

extern "C" void cuda_poolcell_propagate(unsigned int nbChannels,
                                        unsigned int channelsHeight,
                                        unsigned int channelsWidth,
                                        unsigned int strideY,
                                        unsigned int strideX,
                                        const DATA_T* inputs,
                                        unsigned int nbOutputs_,
                                        unsigned int outputsHeight,
                                        unsigned int outputsWidth,
                                        unsigned int nbOutputs,
                                        unsigned int outputOffset,
                                        DATA_T* outputs,
                                        unsigned int poolHeight,
                                        unsigned int poolWidth,
                                        const char* mapping,
                                        Pooling_T pooling,
                                        ActivationFunction_T func,
                                        int shift,
                                        dim3 threadsPerBlocks,
                                        dim3 blocksPerGrid,
                                        bool isProfiled,
                                        float* exec_time,
                                        bool unitMap);

extern "C" void cuda_poolcell_upropagate(unsigned int nbChannels,
                                         unsigned int channelsHeight,
                                         unsigned int channelsWidth,
                                         unsigned int strideY,
                                         unsigned int strideX,
                                         const UDATA_T* inputs,
                                         unsigned int nbOutputs_,
                                         unsigned int outputsHeight,
                                         unsigned int outputsWidth,
                                         unsigned int nbOutputs,
                                         unsigned int outputOffset,
                                         DATA_T* outputs,
                                         unsigned int poolHeight,
                                         unsigned int poolWidth,
                                         const char* mapping,
                                         Pooling_T pooling,
                                         ActivationFunction_T func,
                                         int shift,
                                         dim3 threadsPerBlocks,
                                         dim3 blocksPerGrid,
                                         bool isProfiled,
                                         float* exec_time,
                                         bool unitMap);

extern "C" void cuda_fccell_propagate_2d(unsigned int nbChannels,
                                         unsigned int channelsHeight,
                                         unsigned int channelsWidth,
                                         const DATA_T* inputs,
                                         unsigned int nbOutputs_,
                                         unsigned int nbOutputs,
                                         unsigned int outputOffset,
                                         DATA_T* outputs,
                                         unsigned int nbChannels_,
                                         const BDATA_T* bias,
                                         const WDATA_T* weights,
                                         ActivationFunction_T func,
                                         int shift,
                                         dim3 threadsPerBlocks,
                                         dim3 blocksPerGrid,
                                         bool isProfiled,
                                         float* exec_time);

extern "C" void cuda_fccell_upropagate_2d(unsigned int nbChannels,
                                          unsigned int channelsHeight,
                                          unsigned int channelsWidth,
                                          const UDATA_T* inputs,
                                          unsigned int nbOutputs_,
                                          unsigned int nbOutputs,
                                          unsigned int outputOffset,
                                          DATA_T* outputs,
                                          unsigned int nbChannels_,
                                          const BDATA_T* bias,
                                          const WDATA_T* weights,
                                          ActivationFunction_T func,
                                          int shift,
                                          dim3 threadsPerBlocks,
                                          dim3 blocksPerGrid,
                                          bool isProfiled,
                                          float* exec_time);

extern "C" void cuda_fccell_propagate(unsigned int nbChannels,
                                      const DATA_T* inputs,
                                      unsigned int nbOutputs_,
                                      unsigned int nbOutputs,
                                      unsigned int outputOffset,
                                      DATA_T* outputs,
                                      const BDATA_T* bias,
                                      const WDATA_T* weights,
                                      ActivationFunction_T func,
                                      int shift,
                                      dim3 threadsPerBlocks,
                                      dim3 blocksPerGrid,
                                      bool isProfiled,
                                      float* exec_time);

extern "C" void cuda_fccell_upropagate(unsigned int nbChannels,
                                       const UDATA_T* inputs,
                                       unsigned int nbOutputs_,
                                       unsigned int nbOutputs,
                                       unsigned int outputOffset,
                                       DATA_T* outputs,
                                       const BDATA_T* bias,
                                       const WDATA_T* weights,
                                       ActivationFunction_T func,
                                       int shift,
                                       dim3 threadsPerBlocks,
                                       dim3 blocksPerGrid,
                                       bool isProfiled,
                                       float* exec_time);

extern "C" void cuda_softmaxcell_propagate(unsigned int nbOutputs,
                                          unsigned int outputsHeight,
                                          unsigned int outputsWidth,
                                          unsigned int batchSize,
                                          const DATA_T* inputs,
                                          DATA_T* outputs,
                                          dim3 threadsPerBlocks,
                                          dim3 blocksPerGrid,
                                          bool isProfiled,
                                          float* exec_time);

extern "C" void cuda_spatial_outputs_max(unsigned int nbOutputs,
                                          unsigned int outputsHeight,
                                          unsigned int outputsWidth,
                                          unsigned int batchSize,
                                          DATA_T* inputs,
                                          DATA_T* outputs,
                                          dim3 threadsPerBlocks,
                                          dim3 blocksPerGrid,
                                          bool isProfiled,
                                          float* exec_time);

#endif
