###############################################################################
#            N2D2 Continious Integration and Continious Deployment            #
#                                                                             #
###############################################################################


stages:
  # Build N2D2
  - build
  # Unit test stage
  - test
  # Generate documentation files
  - documentation
  # Deploy N2D2 code to other web interfaces
  - deploy
  # Nightly build stage
  - nightly-build
  # Nightly test stage
  - nightly-test


include:
  - local: '/.gitlab/ci/_global.gitlab-ci.yml'
  - local: '/.gitlab/ci/_rules.gitlab-ci.yml'
  - local: '/.gitlab/ci/build.gitlab-ci.yml'
  - local: '/.gitlab/ci/test.gitlab-ci.yml'
  - local: '/.gitlab/ci/documentation.gitlab-ci.yml'
  - local: '/.gitlab/ci/deploy.gitlab-ci.yml'
  - local: '/.gitlab/ci/nightly-build.gitlab-ci.yml'
  - local: '/.gitlab/ci/nightly-test.gitlab-ci.yml'
