variables:
  GIT_SUBMODULE_STRATEGY: recursive
  OMP_NUM_THREADS: 4

stages:
  - build
  - test
  - deploy

.before_script_template:
  before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..

build:ubuntu:
  extends: .before_script_template
  stage: build
  tags:
    - ubuntu
  script:
    - make -j4
    - cp lib/*.so ../python/
    - make docs -j4
  artifacts:
    paths:
      - docs/_build/html

test:ubuntu:
  extends: .before_script_template
  stage: test
  tags:
    - ubuntu
  script:
#    - cd build
    - make tests -j4
    - make test

test:python_api:
  extends: .before_script_template
  stage: test
  tags:
    - ubuntu
  image: "python:3.7"    
  script:
    - cd ../python
    - pip install -r requirements.txt
    # Run on discovery all tests located in python/tests and discard the stdout to only show the errors/warnings and the results of the tests
    - python3.7 -m unittest discover -s tests -v 1> /dev/null


# HTTP server setup on is154584 (using python simplehttp):
# systemctl config file: /etc/systemd/system/simplehttp.service
# service restart: systemctl restart simplehttp.service
docs:
  stage: test
  script:
    - mkdir -p /local/is154584/www/N2D2/${CI_COMMIT_REF_NAME}
    - cp -r docs/_build/html/* /local/is154584/www/N2D2/${CI_COMMIT_REF_NAME}
  environment:
    name: Documentation
    url: http://is154584.intra.cea.fr:8081/N2D2/${CI_COMMIT_REF_NAME}

# Github deployment
github:
  stage: deploy
  script:
    - git remote show github || git remote add github git@github.com:CEA-LIST/N2D2.git
    - git push github HEAD:master
  environment:
    name: Github
    url: https://github.com/CEA-LIST/N2D2
  only:
    - master

# Github.io deployment
github.io:
  stage: deploy
  script:
    - git -C ../github.io/ pull || git clone git@github.com:CEA-LIST/N2D2-docs.git ../github.io
    - cp -r docs/_build/html/* ../github.io/
    - cd ../github.io
    - git add --all
    - git config user.email "olivier.bichler@cea.fr"
    - git config user.name "gitlab-runner"
    - git diff --quiet && git diff --staged --quiet || git commit -m "${CI_COMMIT_MESSAGE}"
    - git push
  environment:
    name: Github.io
    url: https://cea-list.github.io/N2D2-docs
  only:
    - master
