variables:
  GIT_SUBMODULE_STRATEGY: recursive
  OMP_NUM_THREADS: 4

stages:
  - build
  - test
  - deploy

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

build:ubuntu:
  stage: build
  tags:
    - ubuntu
  script:
    - make -j4
#  artifacts:
#    expire_in: 2 hrs
#    paths:
#      - build/

test:ubuntu:
  stage: test
  tags:
    - ubuntu
  script:
#    - cd build
    - make tests -j4
    - make test

# HTTP server setup on is154584 (using python simplehttp):
# systemctl config file: /etc/systemd/system/simplehttp.service
# service restart: systemctl restart simplehttp.service
docs:
  stage: deploy
  script:
    - make docs -j4
    - cp -r ../docs/_build/html/* /local/is154584/www/N2D2/
  environment:
    name: Documentation
    url: http://is154584.intra.cea.fr:8081/N2D2/
  only:
    - master
