name: linux-gpu

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      USE_CUDA: 1
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Install required libraries
      run: |
        chmod +x ./.github/scripts/install_libraries_ubuntu_20_04.sh
        ./.github/scripts/install_libraries_ubuntu_20_04.sh

    - name: Build N2D2
      run: |
        mkdir build
        cd build
        cmake ..
        make -j2