################################################################################
# Centralized definitions of common job parameter values.                      #
# Parameters with many optional configurations may be in separate files.       #
#                                                                              #
################################################################################


variables:
  GIT_SUBMODULE_STRATEGY: recursive
  OMP_NUM_THREADS: 4
  GIT_SSL_NO_VERIFY: 1
  N2D2_DATA: /nvme0/DATABASE


# Generic before_script to run common jobs
.before_script_template:
  before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..


# Before_script used to perform coverage tests
.before_script_coverage:
  before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Coverage ..


