################################################################################
# Centralized definitions of common job parameter values.                      #
# Parameters with many optional configurations may be in separate files.       #
#                                                                              #
################################################################################


variables:
  GIT_SUBMODULE_STRATEGY: recursive
  OMP_NUM_THREADS: 4
  GIT_SSL_NO_VERIFY: 1
  GIT_SSH_COMMAND: "ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

# Generic before_script to run common jobs
.before_script_template:
  before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ..


# Before_script used to run python jobs
.before_script_python:
  before_script:
    - cd python
    # Creating a new virtualenv
    - pip install virtualenv
    - virtualenv -p python3.8 venv
    - shopt -s expand_aliases
    - alias python='venv/bin/python3.8'
    # -> verify env is clean
    - python -m pip freeze
    - python -m pip install -r requirements.txt
    - python -m pip install -r keras_to_n2d2/requirements.txt
    - python -m pip install -r pytorch_to_n2d2/requirements.txt
    # -> Check installed lib
    - python -m pip freeze
    # Copy export folder in n2d2 folder
    - cp -r ../export n2d2


# Before_script used to perform coverage tests
.before_script_coverage:
  before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Coverage ..

