####################################################################################################
# List of conditions to run CI/CD jobs                                                             #
# References:                                                                                      #
# * https://docs.gitlab.com/ee/ci/yaml/#rules                                                      #
# * https://docs.gitlab.com/ee/ci/variables/README.html#syntax-of-environment-variable-expressions #
#                                                                                                  #
####################################################################################################

##############
# Conditions #
##############

.rules-element:if-default-branch: &if-default-branch
  if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

.rules-element:if-schedule-pipeline: &if-schedule-pipeline
  if: '$CI_PIPELINE_SOURCE == "schedule"'

.rules-element:if-not-schedule-pipeline: &if-not-schedule-pipeline
  if: '$CI_PIPELINE_SOURCE != "schedule"'


########################
# Default branch rules #
########################

.rules:all-branches-not-schedule:
  rules:
    - *if-not-schedule-pipeline

# Jobs that run only on the default branch (which should be 'master')
.rules:default-branch-only:
  rules:
  - *if-default-branch 
  - *if-not-schedule-pipeline


##################
# Schedule rules #
##################

.rules:default-branch-only-schedule:
  rules:
    - *if-default-branch 
    - *if-schedule-pipeline

.rules:schedule-python-tests:
  rules:
    - *if-default-branch 
    - *if-schedule-pipeline
    - if: '$PY_TEST_NIGHTLY'
