####################################################################################################
# List of conditions to run CI/CD jobs                                                             #
# References:                                                                                      #
# * https://docs.gitlab.com/ee/ci/yaml/#rules                                                      #
# * https://docs.gitlab.com/ee/ci/variables/README.html#syntax-of-environment-variable-expressions #
#                                                                                                  #
####################################################################################################


########################
# Default branch rules #
########################

.rules:all-branches-not-schedule:
  rules:
    - if: '$CI_PIPELINE_SOURCE != "schedule"'

# Jobs that run only on the default branch (which should be 'master')
.rules:default-branch-only:
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH &&
           $CI_PIPELINE_SOURCE != "schedule"'


##################
# Schedule rules #
##################

.rules:default-branch-only-schedule:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'

.rules:schedule-python-tests:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && 
           $PY_TEST_NIGHTLY'
