generate-docs:
  extends: 
    - .before_script_template
  stage: documentation
  tags:
    - ubuntu
  script:
    - make docs -j4
  dependencies:
    - build:ubuntu
  artifacts:
    paths:
      - docs/_build/html
