generate-docs:
  extends: 
    - .before_script_template
    - .rules:all-branches-not-schedule
  stage: documentation
  tags:
    - ubuntu
  script:
    - make docs -j4
  artifacts:
    paths:
      - docs/_build/html
