test:ubuntu:
  extends: 
    - .before_script_template
  stage: test
  tags:
    - ubuntu
  script:
    - make tests -j4
    - make test


test:python_api:
  stage: test
  tags:
    - ubuntu
  image: "python:3.7"
  script:
    - cd python
    - docker build -t python_api:0.0.1 .
    - docker container create --name python_test_ci \
    --cpus=4 --runtime=nvidia -it python_api:0.0.1 /bin/bash
    - docker container run python_test_ci

