test:ubuntu:
  extends: 
    - .before_script_template
  stage: test
  tags:
    - ubuntu
  script:
    - make tests -j4
    - make test


test:python_api:
  extends: 
    - .before_script_template
  stage: test
  tags:
    - ubuntu
  image: "python:3.7"
  script:
    - cd ../python

    - pip install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    
    - pip install -r requirements.txt
    - pip install -r pytorch_interoperability/requirements.txt
    - pip install -r keras_interoperability/requirements.txt
    # Run on discovery all tests located in python/tests and discard the stdout 
    # only to show the errors/warnings and the results of the tests
    - python3.7 -m unittest discover -s tests -v -b 1> /dev/null 
