test:ubuntu:
  extends: 
    - .before_script_template
  stage: test
  variables:
    CTEST_OUTPUT_ON_FAILURE: 1
  tags:
    - ubuntu
  script:
    - make tests -j4
    - make test


test:python_api:
  stage: test
  tags:
    - ubuntu
  image: "python:3.7"
  script:
    #- make -j4
    #- cp lib/*.so ../python/
    - cd ../python
    - pip install -r requirements.txt
    # Run on discovery all tests located in python/tests and discard the stdout 
    # only to show the errors/warnings and the results of the tests
    - python3.7 -m unittest discover -s tests -v -b 1> /dev/null 

static_analysis:python_api:
  stage: test
  allow_failure: true
  tags:
    - ubuntu
  image: "python:3.7"
  before_script:
    # Allow to use aliases in non interactive mode.
    - shopt -s expand_aliases 
    ### PyLint Warning to Ignore ###
    # I1101 c-extension-no-member : C extension not found
    # C0103 invalid-name : Name doesn't fit python convention (camel)
    # F0401 import-error : Unable to import
    # E0611 no-name-in-module : Used when a name cannot be found in a module.

    - alias run_linting='pylint -d I1101 -d C0103 -d F0401 -d C0326'

  script:
    - cd python
    - pip install pylint
    - pip install pylint-exit
    - run_linting n2d2 pytorch_interoperability keras_interoperability || pylint-exit $? 
