test:ubuntu:
  extends: 
    - .before_script_template
    - .rules:all-branches-not-schedule
  stage: test
  variables:
    CTEST_OUTPUT_ON_FAILURE: 1
  tags:
    - ubuntu
  script:
    - make tests -j4
    - make test


test:python_api:
  extends: 
    - .before_script_python
    - .rules:all-branches-not-schedule
  stage: test
  tags:
    - ubuntu  
  before_script: 
  script:
    # Run on discovery all tests located in python/tests and discard the stdout 
    # only to show the errors/warnings and the results of the tests
    - python -m unittest discover -s tests -v -b 1> /dev/null 


static_analysis:python_api:
  extends:
    - .rules:all-branches-not-schedule
  stage: test
  allow_failure: true
  tags:
    - ubuntu
  image: "python:3.7"
  script:
    - cd python
    - pip install pylint
    - pip install pylint-exit
    - pylint --rcfile=.pylintrc n2d2 pytorch_interoperability keras_interoperability || pylint-exit $? 
